spring:
  datasource:
#    url: jdbc:mysql://192.168.3.85:3306/simes?useServerPrepStmts=false&rewriteBatchedStatements=true
#    username: root
#    password: 123qwe!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  data:
    mongodb:
      uri: mongodb://admin:123qwe@192.168.3.85:27017/simes?authSource=admin&authMechanism=SCRAM-SHA-1
  redis:
    database: 0
    host: 192.168.3.85
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.85:8848,192.168.3.86:8848,192.168.3.87:8848
        namespace: f1bf1f79-226f-4368-8e0d-4b7514f5203b
  kafka:
    bootstrap-servers: 192.168.3.85:9092
    producer:
      batch-size: 16
      retries: 3
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: simes
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  configuration:
    call-setters-on-nulls: true
    default-executor-type: reuse
    use-generated-keys: false
    cache-enabled: false
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# logback
logging:
  level:
    root: INFO
  config: classpath:logback.xml

# token存活时间
tokenAliveTime: 30
# mysql的url
mysqlUrl: jdbc:mysql://192.168.3.85:3306/simes?useServerPrepStmts=false&rewriteBatchedStatements=true
# mysql的username
mysqlUsername: root
# mysql的password
mysqlPassword: 123qwe!@#
